version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 16
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - '..:/workspace:cached'
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:database

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ignite
      POSTGRES_USER: docker
      POSTGRES_DB: rentx
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080


  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 800:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password


volumes:
    pgdata:
      driver: local